apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-app-alert
  labels:
    release: monitoring
spec:
  groups:
  - name: devops-app-alerts
    rules:
    - alert: HighCPUUsage
      expr: |
        sum(rate(container_cpu_usage_seconds_total{pod=~"devops-app.*"}[2m]))
        /
        sum(kube_pod_container_resource_requests_cpu_cores{pod=~"devops-app.*"})
        > 0.7
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is above 70% for devops-app"
